build:
  environment:
    variables:
      MOZ_HEADLESS: 1
  nodes:
    coverage:
      project_setup:
        before:
          - command: npm install pm2@latest -g
          - command: pm2 start ecosystem.config.js
      tests:
        override:
          - command: npm test
            # coverage:
            #   file: coverage/clover.xml
            #   format: clover
