build:
  environment:
    variables:
      MOZ_HEADLESS: "1"
  nodes:
    coverage:
      tests:
        override:
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover
