dist: xenial

language: node_js

node_js:
    - "node"

git:
    submodules: false

before_install:
    - export MOZ_HEADLESS=1

before_script:
    - npm install
    - npm install pm2@latest -g
    - pm2 start ecosystem.config.js

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
