dist: xenial

language: node_js

node_js:
    - "node"
    - "10"
    - "8"
    - "6"

# sudo: false

git:
    submodules: false

before_script:
    - npm install
    - npm install pm2@latest -g
    - pm2 start ecosystem.config.js

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
